export const resources = {
    en: {
        translation: {
            // Login Screen
            "signInToContinue": "Sign in to continue",
            "username": "Username",
            " Email or Mobile": "Email or Mobile",
            "password": "Password",
            "login": "Login",
            "createNewAccount": "Create a new account?",

            // Registration Screen
            "createYourAccount": "Create your account",
            "name": "Name",
            "email": "Email",
            "phoneNumber": "Phone Number",
            "confirmPassword": "Confirm Password",
            "register": "Register",
            "alreadyHaveAccount": "Already have an account?",

            // Dashboard Screen
            "agentDetails": "Agent Details",
            "agentId": "Agent ID",
            "agentName": "Agent Name",
            "market": "Market",
            "date": "Date",
            "selectCategory": "Select Category",
            "single": "Single",
            "jodi": "Jodi",
            "enterNumber": "Enter Number",
            "enterAmount": "Enter Amount",
            "anotherNumber": "Another Number",
            "amountSecond": "Amount Second",
            "submit": "Submit",
            "payment": "Payment",

            // Explore Screen
            "filter": "Filter By",
            "sort": "Sort By",
            "noProduct": "No Product",

            // Validation Messages
            "validationError": "Validation Error",
            "nameRequired": "Name is required",
            "invalidEmail": "Invalid email address",
            "invalidPhone": "Invalid phone number (10 digits required)",
            "passwordLength": "Password must be at least 8 characters",
            "passwordsDoNotMatch": "Passwords do not match",
            "success": "Success",
            "registrationSuccessful": "Registration successful!",


            // Login validation messages
            "usernameRequired": "Username is required",
            "usernameTooShort": "Username must be at least 4 characters",
            "passwordRequired": "Password is required",
            "passwordTooShort": "Password must be at least 6 characters",
            "loginFailed": "Login Failed",

            "close": "Close",
            "save_changes": "Save changes",
            "edit_entry": "Edit Entry",
            "confirm_deletion": "Confirm Deletion",
            "confirm_delete_message": "Are you sure you want to delete this entry?",
            "cancel": "Cancel",
            "delete": "Delete",
            "dashboard": "Dashboard",
            "myaccount": "My Account",
            "logout": "Logout",
            "setting": "Settings",

            // Market Countdown
            "openMarket": "Open Market",
            "closeMarket": "Close Market",
            "marketClosed": "Market Closed",
            "hours": "HR",
            "minutes": "MIN",
            "seconds": "SEC",

            // My Wallet
            "latestTransactions": "Latest Transactions",
            "viewAll": "View All",
            "moneyAdded": "Money Added",
            "moneyWithdrawn": "Amount Played",
            "tryAgain": "Try Again",
            "continue": "Continue",

            // Result Screen
            "congratulations": "Congratulations!",
            "youWon": "You Won",
            "betterluck": "Better Luck",
            "nextTime": "Next Time!",

            // Customer List
            "customers": "Customers",
            "searchCustomers": "Search customers...",
            "addCustomer": "Add Customer",
            "editCustomer": "Edit Customer",
            "deleteCustomer": "Delete Customer",
            "deleteCustomerConfirm": "Are you sure you want to delete this customer?",
            "cancel": "Cancel",
            "delete": "Delete",
            "save": "Save",
            "name": "Name",
            "enterName": "Enter name",
            "email": "Email",
            "enterEmail": "Enter email",
            "phoneNumber": "Phone Number",
            "enterPhone": "Enter phone number",
            "password": "Password",
            "enterPassword": "Enter password",
            "confirmPassword": "Confirm Password",
            "confirmPasswordPlaceholder": "Confirm password",
            "optional": "(Optional)",
            "noCustomersFound": "No customers found",
            "customerUpdated": "Customer updated successfully",
            "customerCreated": "Customer created successfully",
            "error": "Error",
            "nameRequired": "Name is required",
            "invalidEmail": "Invalid email address",
            "invalidPhone": "Invalid phone number (10 digits required)",
            "passwordLength": "Password must be at least 8 characters",
            "passwordsDoNotMatch": "Passwords do not match",

            "selectLanguage": "Select Language",
            "reports": "Reports",
            "weeklyReport": "Weekly Report",
            "verifyReport": "Verify Report",
            "addPaymentReport": "Add Payment Report",
            "addButtonReport": "Add Button Report",
            "dailyResult": "Daily Result",
            "result": "Result",
            "agentList": "Agent List",
            "clientList": "Client List",
            "customerlist": "Customer List",
            "mywallet": "My Wallet",

            // Dashboard Screen Additional Translations
            "enterGunule": "Enter Gunule",
            "saralPanNumber": "Saral Pan Number",
            "ultaPanNumber": "Ulta Pan Number",
            "addSaralPan": "Add Saral-Pan",
            "addGunule": "Add Gunule",
            "number": "Number",
            "amount": "Amount",
            "action": "Action",
            "gunule": "Gunule",
            "totalAmount": "Total Amount",
            "openAmount": "Open Amount",
            "closeAmount": "Close Amount",
            "payNow": "Pay Now",
            "confirmPayment": "Confirm Payment",
            "paymentMessage": "You are about to pay ₹{amount} for {count} entries.",
            "selectAtLeastOne": "Please select at least one entry to pay",
            "confirmDelete": "Are you sure you want to delete this entry?",
            "invalidNumber": "Invalid number format for {category} category",
            "pleaseEnterBoth": "Please enter both number and amount",
            "addNumber": "Add Number",
            "removeNumber": "Remove Number",

            // Settings Screen - Password Change
            "changePassword": "Change Password",
            "newPassword": "New Password",
            "updatePassword": "Update Password",
            "updating": "Updating...",
            "passwordChangedSuccessfully": "Password changed successfully",
            "passwordChangeFailed": "Failed to change password",
            "allFieldsRequired": "All fields are required",

            // Registration validation messages
            "registrationFailed": "Registration failed. Please try again."
        }
    },
    hi: {
        translation: {
            // Login Screen
            "signInToContinue": "जारी रखने के लिए साइन इन करें",
            "username": "उपयोगकर्ता नाम",
            "Email or Mobile": "ईमेल या मोबाइल",
            "password": "पासवर्ड",
            "login": "लॉगिन",
            "createNewAccount": "नया खाता बनाएं?",

            // Registration Screen
            "createYourAccount": "अपना खाता बनाएं",
            "name": "नाम",
            "email": "ईमेल",
            "phoneNumber": "फोन नंबर",
            "confirmPassword": "पासवर्ड की पुष्टि करें",
            "register": "रजिस्टर",
            "alreadyHaveAccount": "क्या आपके पास पहले से एक खाता मौजूद है?",

            // Dashboard Screen
            "agentDetails": "एजेंट विवरण",
            "agentId": "एजेंट आईडी",
            "agentName": "एजेंट का नाम",
            "market": "बाजार",
            "date": "तारीख",
            "selectCategory": "श्रेणी चुनें",
            "single": "सिंगल",
            "jodi": "जोड़ी",
            "enterNumber": "नंबर दर्ज करें",
            "enterAmount": "राशि दर्ज करें",
            "anotherNumber": "अन्य नंबर",
            "amountSecond": "दूसरी राशि",
            "submit": "सबमिट",
            "payment": "भुगतान",

            // Explore Screen
            "filter": "फ़िल्टर करें",
            "sort": "क्रमबद्ध करें",
            "noProduct": "कोई उत्पाद नहीं",

            // Validation Messages
            "validationError": "मान्यता त्रुटि",
            "nameRequired": "नाम आवश्यक है",
            "invalidEmail": "अमान्य ईमेल पता",
            "invalidPhone": "अमान्य फोन नंबर (10 अंक आवश्यक)",
            "passwordLength": "पासवर्ड कम से कम 8 अक्षर का होना चाहिए",
            "passwordsDoNotMatch": "पासवर्ड मेल नहीं खाते",
            "success": "सफलता",
            "registrationSuccessful": "पंजीकरण सफल!",

            // Login validation messages
            "usernameRequired": "उपयोगकर्ता नाम आवश्यक है",
            "usernameTooShort": "उपयोगकर्ता नाम कम से कम 4 अक्षर का होना चाहिए",
            "passwordRequired": "पासवर्ड आवश्यक है",
            "passwordTooShort": "पासवर्ड कम से कम 6 अक्षर का होना चाहिए",
            "loginFailed": "लॉगिन विफल",

            "close": "बंद करें",
            "save_changes": "परिवर्तन सहेजें",
            "edit_entry": "प्रविष्टि संपादित करें",
            "confirm_deletion": "हटाने की पुष्टि करें",
            "confirm_delete_message": "क्या आप वाकई इस प्रविष्टि को हटाना चाहते हैं?",
            "cancel": "रद्द करें",
            "delete": "हटाएं",
            "dashboard": "डैशबोर्ड",
            "myaccount": "मेरा खाता",
            "logout": "लॉग आउट",
            "setting": "सेटिंग्स",

            // Market Countdown
            "openMarket": "खुला बाजार",
            "closeMarket": "बंद बाजार",
            "marketClosed": "बाजार बंद",
            "hours": "घंटे",
            "minutes": "मिनट",
            "seconds": "सेकंड",

            // My Wallet
            "latestTransactions": "नवीनतम लेनदेन",
            "viewAll": "सभी देखें",
            "moneyAdded": "पैसा जोड़ा गया",
            "moneyWithdrawn": "खेला गया राशि",
            "tryAgain": "पुनः प्रयास करें",
            "continue": "जारी रखें",

            // Result Screen
            "congratulations": "बधाई हो!",
            "youWon": "आप जीते",
            "betterluck": "बेहतर किस्मत",
            "nextTime": "अगली बार!",

            // Customer List
            "customers": "ग्राहक",
            "searchCustomers": "ग्राहकों को खोजें...",
            "addCustomer": "ग्राहक जोड़ें",
            "editCustomer": "ग्राहक संपादित करें",
            "deleteCustomer": "ग्राहक हटाएं",
            "deleteCustomerConfirm": "क्या आप वाकई इस ग्राहक को हटाना चाहते हैं?",
            "cancel": "रद्द करें",
            "delete": "हटाएं",
            "save": "सहेजें",
            "name": "नाम",
            "enterName": "नाम दर्ज करें",
            "email": "ईमेल",
            "enterEmail": "ईमेल दर्ज करें",
            "phoneNumber": "फोन नंबर",
            "enterPhone": "फोन नंबर दर्ज करें",
            "password": "पासवर्ड",
            "enterPassword": "पासवर्ड दर्ज करें",
            "confirmPassword": "पासवर्ड की पुष्टि करें",
            "confirmPasswordPlaceholder": "पासवर्ड की पुष्टि करें",
            "optional": "(वैकल्पिक)",
            "noCustomersFound": "कोई ग्राहक नहीं मिला",
            "customerUpdated": "ग्राहक सफलतापूर्वक अपडेट किया गया",
            "customerCreated": "ग्राहक सफलतापूर्वक बनाया गया",
            "error": "त्रुटि",
            "nameRequired": "नाम आवश्यक है",
            "invalidEmail": "अमान्य ईमेल पता",
            "invalidPhone": "अमान्य फोन नंबर (10 अंक आवश्यक)",
            "passwordLength": "पासवर्ड कम से कम 8 अक्षर का होना चाहिए",
            "passwordsDoNotMatch": "पासवर्ड मेल नहीं खाते",

            "selectLanguage": "भाषा चुनें",
            "reports": "रिपोर्ट्स",
            "weeklyReport": "साप्ताहिक रिपोर्ट",
            "verifyReport": "सत्यापन रिपोर्ट",
            "addPaymentReport": "भुगतान रिपोर्ट जोड़ें",
            "addButtonReport": "बटन रिपोर्ट जोड़ें",
            "dailyResult": "दैनिक परिणाम",
            "result": "परिणाम",
            "agentList": "एजेंट सूची",
            "clientList": "क्लाइंट सूची",
            "customerlist": "ग्राहक सूची",
            "mywallet": "मेरा वॉलेट",

            // Dashboard Screen Additional Translations
            "enterGunule": "गुनुले दर्ज करें",
            "saralPanNumber": "सरल पैन नंबर",
            "ultaPanNumber": "उल्टा पैन नंबर",
            "addSaralPan": "सरल-पैन जोड़ें",
            "addGunule": "गुनुले जोड़ें",
            "number": "नंबर",
            "amount": "राशि",
            "action": "कार्रवाई",
            "gunule": "गुनुले",
            "totalAmount": "कुल राशि",
            "openAmount": "खुली राशि",
            "closeAmount": "बंद राशि",
            "payNow": "अभी भुगतान करें",
            "confirmPayment": "भुगतान की पुष्टि करें",
            "paymentMessage": "आप {count} प्रविष्टियों के लिए ₹{amount} का भुगतान करने वाले हैं।",
            "selectAtLeastOne": "कृपया भुगतान करने के लिए कम से कम एक प्रविष्टि चुनें",
            "confirmDelete": "क्या आप वाकई इस प्रविष्टि को हटाना चाहते हैं?",
            "invalidNumber": "{category} श्रेणी के लिए अमान्य नंबर प्रारूप",
            "pleaseEnterBoth": "कृपया नंबर और राशि दोनों दर्ज करें",
            "addNumber": "नंबर जोड़ें",
            "removeNumber": "नंबर हटाएं",

            // Settings Screen - Password Change
            "changePassword": "पासवर्ड बदलें",
            "newPassword": "नया पासवर्ड",
            "updatePassword": "पासवर्ड अपडेट करें",
            "updating": "अपडेट हो रहा है...",
            "passwordChangedSuccessfully": "पासवर्ड सफलतापूर्वक बदल दिया गया है",
            "passwordChangeFailed": "पासवर्ड बदलने में विफल",
            "allFieldsRequired": "सभी फ़ील्ड आवश्यक हैं",

            // Registration validation messages
            "registrationFailed": "पंजीकरण विफल हुआ। कृपया पुन: प्रयास करें।"
        }
    },
    mr: {
        translation: {
            // Login Screen
            "signInToContinue": "सुरू ठेवण्यासाठी साइन इन करा",
            "username": "वापरकर्तानाव",
            "Email or Mobile": "ईमेल किंवा मोबाइल",
            "password": "पासवर्ड",
            "login": "लॉगिन",
            "createNewAccount": "नवीन खाते तयार करा?",

            // Registration Screen
            "createYourAccount": "आपले खाते तयार करा",
            "name": "नाव",
            "email": "ईमेल",
            "phoneNumber": "फोन नंबर",
            "confirmPassword": "पासवर्डची पुष्टी करा",
            "register": "नोंदणी करा",
            "alreadyHaveAccount": "आधीपासूनच खाते आहे?",

            // Dashboard Screen
            "agentDetails": "एजंट तपशील",
            "agentId": "एजंट आयडी",
            "agentName": "एजंटचे नाव",
            "market": "बाजार",
            "date": "तारीख",
            "selectCategory": "श्रेणी निवडा",
            "single": "सिंगल",
            "jodi": "जोडी",
            "enterNumber": "नंबर प्रविष्ट करा",
            "enterAmount": "रक्कम प्रविष्ट करा",
            "anotherNumber": "दुसरा नंबर",
            "amountSecond": "दुसरी रक्कम",
            "submit": "सबमिट करा",
            "payment": "पेमेंट",

            // Explore Screen
            "filter": "फिल्टर करा",
            "sort": "क्रमवारी लावा",
            "noProduct": "कोणतेही उत्पादन नाही",

            // Validation Messages
            "validationError": "वैधता त्रुटी",
            "nameRequired": "नाव आवश्यक आहे",
            "invalidEmail": "अवैध ईमेल पत्ता",
            "invalidPhone": "अवैध फोन नंबर (10 अंक आवश्यक)",
            "passwordLength": "पासवर्ड किमान 8 वर्णांचा असावा",
            "passwordsDoNotMatch": "पासवर्ड जुळत नाहीत",
            "success": "यश",
            "registrationSuccessful": "नोंदणी यशस्वी!",

            // Login validation messages
            "usernameRequired": "वापरकर्तानाव आवश्यक आहे",
            "usernameTooShort": "वापरकर्तानाव किमान 4 वर्णांचे असावे",
            "passwordRequired": "पासवर्ड आवश्यक आहे",
            "passwordTooShort": "पासवर्ड किमान 6 वर्णांचे असावे",
            "loginFailed": "लॉगिन अयशस्वी",

            "close": "बंद करा",
            "save_changes": "बदल जतन करा",
            "edit_entry": "नोंद संपादित करा",
            "confirm_deletion": "हटवण्याची पुष्टी करा",
            "confirm_delete_message": "आपण ही नोंद हटवू इच्छिता याची खात्री आहे?",
            "cancel": "रद्द करा",
            "delete": "हटवा",
            "dashboard": "डॅशबोर्ड",
            "myaccount": "माझे खाते",
            "logout": "बाहेर पडा",
            "setting": "सेटिंग्ज",

            // Market Countdown
            "openMarket": "उघडा बाजार",
            "closeMarket": "बंद बाजार",
            "marketClosed": "बाजार बंद",
            "hours": "तास",
            "minutes": "मिनिटे",
            "seconds": "सेकंद",

            // My Wallet
            "latestTransactions": "नवीनतम व्यवहार",
            "viewAll": "सर्व पहा",
            "moneyAdded": "पैसे जोडले",
            "moneyWithdrawn": "लावलेली रक्कम",
            "tryAgain": "पुन्हा प्रयत्न करा",
            "continue": "सुरू ठेवा",

            // Result Screen
            "congratulations": "अभिनंदन!",
            "youWon": "तुम्ही जिंकलात",
            "betterluck": "चांगली किस्मत",
            "nextTime": "पुढील वेळी!",

            // Customer List
            "customers": "ग्राहक",
            "searchCustomers": "ग्राहक शोधा...",
            "addCustomer": "ग्राहक जोडा",
            "editCustomer": "ग्राहक संपादित करा",
            "deleteCustomer": "ग्राहक हटवा",
            "deleteCustomerConfirm": "आपण हा ग्राहक हटवू इच्छिता याची खात्री आहे?",
            "cancel": "रद्द करें",
            "delete": "हटवा",
            "save": "जतन करा",
            "name": "नाव",
            "enterName": "नाव प्रविष्ट करा",
            "email": "ईमेल",
            "enterEmail": "ईमेल प्रविष्ट करा",
            "phoneNumber": "फोन नंबर",
            "enterPhone": "फोन नंबर प्रविष्ट करा",
            "password": "पासवर्ड",
            "enterPassword": "पासवर्ड प्रविष्ट करा",
            "confirmPassword": "पासवर्डची पुष्टी करा",
            "confirmPasswordPlaceholder": "पासवर्डची पुष्टी करा",
            "optional": "(पर्यायी)",
            "noCustomersFound": "कोणतेही ग्राहक सापडले नाहीत",
            "customerUpdated": "ग्राहक यशस्वीरित्या अद्यतनित केला",
            "customerCreated": "ग्राहक यशस्वीरित्या तयार केला",
            "error": "त्रुटी",
            "nameRequired": "नाव आवश्यक आहे",
            "invalidEmail": "अवैध ईमेल पत्ता",
            "invalidPhone": "अवैध फोन नंबर (10 अंक आवश्यक)",
            "passwordLength": "पासवर्ड किमान 8 वर्णांचा असावा",
            "passwordsDoNotMatch": "पासवर्ड जुळत नाहीत",

            "selectLanguage": "भाषा निवडा",
            "reports": "अहवाल",
            "weeklyReport": "साप्ताहिक अहवाल",
            "verifyReport": "पडताळ अहवाल",
            "addPaymentReport": "पेमेंट अहवाल जोडा",
            "addButtonReport": "बटण अहवाल जोडा",
            "dailyResult": "दैनिक निकाल",
            "result": "निकाल",
            "agentList": "एजंट यादी",
            "clientList": "क्लायंट यादी",
            "customerlist": "ग्राहक यादी",
            "mywallet": "माझे वॉलेट",

            // Dashboard Screen Additional Translations
            "enterGunule": "गुनुले प्रविष्ट करा",
            "saralPanNumber": "सरळ पॅन क्रमांक",
            "ultaPanNumber": "उलटा पॅन क्रमांक",
            "addSaralPan": "सरळ-पॅन जोडा",
            "addGunule": "गुनुले जोडा",
            "number": "क्रमांक",
            "amount": "रक्कम",
            "action": "कृती",
            "gunule": "गुनुले",
            "totalAmount": "एकूण रक्कम",
            "openAmount": "खुली रक्कम",
            "closeAmount": "बंद रक्कम",
            "payNow": "आता पैसे द्या",
            "confirmPayment": "पेमेंट पुष्टी करा",
            "paymentMessage": "तुम्ही {count} नोंदींसाठी ₹{amount} चे पेमेंट करणार आहात.",
            "selectAtLeastOne": "कृपया पेमेंट करण्यासाठी किमान एक नोंद निवडा",
            "confirmDelete": "तुम्हाला खात्री आहे की तुम्ही ही नोंद हटवू इच्छिता?",
            "invalidNumber": "{category} श्रेणीसाठी अवैध क्रमांक स्वरूप",
            "pleaseEnterBoth": "कृपया क्रमांक आणि रक्कम दोन्ही प्रविष्ट करा",
            "addNumber": "क्रमांक जोडा",
            "removeNumber": "क्रमांक काढा",

            // Settings Screen - Password Change
            "changePassword": "पासवर्ड बदला",
            "newPassword": "नवीन पासवर्ड",
            "updatePassword": "पासवर्ड अपडेट करा",
            "updating": "अपडेट होत आहे...",
            "passwordChangedSuccessfully": "पासवर्ड यशस्वीरित्या बदलला",
            "passwordChangeFailed": "पासवर्ड बदलण्यात अयशस्वी",
            "allFieldsRequired": "सर्व फील्ड आवश्यक आहेत",

            // Registration validation messages
            "registrationFailed": "नोंदणी अयशस्वी झाली. कृपया पुन्हा प्रयत्न करा."
        }
    },
    kn: {
        translation: {
            // Login Screen
            "signInToContinue": "ಮುಂದುವರಿಯಲು ಸೈನ್ ಇನ್ ಮಾಡಿ",
            "username": "ಬಳಕೆದಾರ ಹೆಸರು",
            "Email or Mobile": "ಇಮೇಲ್ ಅಥವಾ ಮೊಬೈಲ್",
            "password": "ಪಾಸ್‌ವರ್ಡ್",
            "login": "ಲಾಗಿನ್",
            "createNewAccount": "ಹೊಸ ಖಾತೆಯನ್ನು ರಚಿಸಿ?",

            // Registration Screen
            "createYourAccount": "ನಿಮ್ಮ ಖಾತೆಯನ್ನು ರಚಿಸಿ",
            "name": "ಹೆಸರು",
            "email": "ಇಮೇಲ್",
            "phoneNumber": "ಫೋನ್ ಸಂಖ್ಯೆ",
            "confirmPassword": "ಪಾಸ್‌ವರ್ಡ್ ದೃಢೀಕರಿಸಿ",
            "register": "ನೋಂದಣಿ",
            "alreadyHaveAccount": "ಈಗಾಗಲೇ ಖಾತೆ ಹೊಂದಿದ್ದೀರಾ?",

            // Dashboard Screen
            "agentDetails": "ಏಜೆಂಟ್ ವಿವರಗಳು",
            "agentId": "ಏಜೆಂಟ್ ಐಡಿ",
            "agentName": "ಏಜೆಂಟ್ ಹೆಸರು",
            "market": "ಮಾರುಕಟ್ಟೆ",
            "date": "ದಿನಾಂಕ",
            "selectCategory": "ವರ್ಗವನ್ನು ಆಯ್ಕೆಮಾಡಿ",
            "single": "ಸಿಂಗಲ್",
            "jodi": "ಜೋಡಿ",
            "enterNumber": "ಸಂಖ್ಯೆಯನ್ನು ನಮೂದಿಸಿ",
            "enterAmount": "ಮೊತ್ತವನ್ನು ನಮೂದಿಸಿ",
            "anotherNumber": "ಮತ್ತೊಂದು ಸಂಖ್ಯೆ",
            "amountSecond": "ಎರಡನೇ ಮೊತ್ತ",
            "submit": "ಸಲ್ಲಿಸು",
            "payment": "ಪಾವತಿ",

            // Explore Screen
            "filter": "ಫಿಲ್ಟರ್ ಮಾಡಿ",
            "sort": "ವಿಂಗಡಿಸಿ",
            "noProduct": "ಯಾವುದೇ ಉತ್ಪನ್ನವಿಲ್ಲ",

            // Validation Messages
            "validationError": "ಮಾನ್ಯತೆ ದೋಷ",
            "nameRequired": "ಹೆಸರು ಅಗತ್ಯವಿದೆ",
            "invalidEmail": "ಅಮಾನ್ಯ ಇಮೇಲ್ ವಿಳಾಸ",
            "invalidPhone": "ಅಮಾನ್ಯ ಫೋನ್ ಸಂಖ್ಯೆ (10 ಅಂಕಿಗಳು ಅಗತ್ಯವಿದೆ)",
            "passwordLength": "ಪಾಸ್‌ವರ್ಡ್ ಕನಿಷ್ಠ 8 ಅಕ್ಷರಗಳನ್ನು ಹೊಂದಿರಬೇಕು",
            "passwordsDoNotMatch": "ಪಾಸ್‌ವರ್ಡ್‌ಗಳು ಹೊಂದಿಕೆಯಾಗುವುದಿಲ್ಲ",
            "success": "ಯಶಸ್ಸು",
            "registrationSuccessful": "ನೋಂದಣಿ ಯಶಸ್ವಿಯಾಗಿದೆ!",

            // Login validation messages
            "usernameRequired": "ಬಳಕೆದಾರ ಹೆಸರು ಅಗತ್ಯವಿದೆ",
            "usernameTooShort": "ಬಳಕೆದಾರ ಹೆಸರು ಕನಿಷ್ಠ 4 ಅಕ್ಷರಗಳನ್ನು ಹೊಂದಿರಬೇಕು",
            "passwordRequired": "ಪಾಸ್‌ವರ್ಡ್ ಅಗತ್ಯವಿದೆ",
            "passwordTooShort": "ಪಾಸ್‌ವರ್ಡ್ ಕನಿಷ್ಠ 6 ಅಕ್ಷರಗಳನ್ನು ಹೊಂದಿರಬೇಕು",
            "loginFailed": "ಲಾಗಿನ್ ವಿಫಲವಾಗಿದೆ",

            "close": "ಮುಚ್ಚಿರಿ",
            "save_changes": "ಬದಲಾವಣೆಗಳನ್ನು ಉಳಿಸಿ",
            "edit_entry": "ನಮೂದನ್ನು ಸಂಪಾದಿಸಿ",
            "confirm_deletion": "ಅಳಿಸುವಿಕೆಯನ್ನು ದೃಢೀಕರಿಸಿ",
            "confirm_delete_message": "ಈ ನಮೂದನ್ನು ಅಳಿಸಲು ನೀವು ಖಚಿತವಾಗಿ ಬಯಸುವಿರಾ?",
            "cancel": "ರದ್ದುಮಾಡಿ",
            "delete": "ಅಳಿಸಿ",
            "dashboard": "ಡ್ಯಾಶ್‌ಬೋರ್ಡ್",
            "myaccount": "ನನ್ನ ಖಾತೆ",
            "logout": "ಲಾಗ್ ಔಟ್",
            "setting": "ಸೆಟ್ಟಿಂಗ್ಸ್",

            // Market Countdown
            "openMarket": "ತೆರೆದ ಮಾರುಕಟ್ಟೆ",
            "closeMarket": "ಮುಚ್ಚಿದ ಮಾರುಕಟ್ಟೆ",
            "marketClosed": "ಮಾರುಕಟ್ಟೆ ಮುಚ್ಚಿದೆ",
            "hours": "ಗಂಟೆಗಳು",
            "minutes": "ನಿಮಿಷಗಳು",
            "seconds": "ಸೆಕೆಂಡುಗಳು",

            // My Wallet
            "latestTransactions": "ಇತ್ತೀಚಿನ ವಹಿವಾಟುಗಳು",
            "viewAll": "ಎಲ್ಲಾ ವೀಕ್ಷಿಸಿ",
            "moneyAdded": "ಹಣವನ್ನು ಸೇರಿಸಲಾಗಿದೆ",
            "moneyWithdrawn": "ಆಡಲಾದ ಮೊತ್ತ",
            "tryAgain": "ಮತ್ತೆ ಪ್ರಯತ್ನಿಸಿ",
            "continue": "ಮುಂದುವರಿಸಿ",

            // Result Screen
            "congratulations": "ಅಭಿನಂದನೆಗಳು!",
            "youWon": "ನೀವು ಗೆದ್ದಿದ್ದೀರಿ",
            "betterluck": "ಉತ್ತಮ ಅದೃಷ್ಟ",
            "nextTime": "ಮುಂದಿನ ಬಾರಿ!",

            // Customer List
            "customers": "ಗ್ರಾಹಕರು",
            "searchCustomers": "ಗ್ರಾಹಕರನ್ನು ಹುಡುಕಿ...",
            "addCustomer": "ಗ್ರಾಹಕರನ್ನು ಸೇರಿಸಿ",
            "editCustomer": "ಗ್ರಾಹಕರನ್ನು ಸಂಪಾದಿಸಿ",
            "deleteCustomer": "ಗ್ರಾಹಕರನ್ನು ಅಳಿಸಿ",
            "deleteCustomerConfirm": "ಈ ಗ್ರಾಹಕರನ್ನು ಅಳಿಸಲು ನೀವು ಖಚಿತವಾಗಿ ಬಯಸುವಿರಾ?",
            "cancel": "ರದ್ದುಮಾಡಿ",
            "delete": "ಅಳಿಸಿ",
            "save": "ಉಳಿಸಿ",
            "name": "ಹೆಸರು",
            "enterName": "ಹೆಸರನ್ನು ನಮೂದಿಸಿ",
            "email": "ಇಮೇಲ್",
            "enterEmail": "ಇಮೇಲ್ ನಮೂದಿಸಿ",
            "phoneNumber": "ಫೋನ್ ಸಂಖ್ಯೆ",
            "enterPhone": "ಫೋನ್ ಸಂಖ್ಯೆಯನ್ನು ನಮೂದಿಸಿ",
            "password": "ಪಾಸ್‌ವರ್ಡ್",
            "enterPassword": "ಪಾಸ್‌ವರ್ಡ್ ನಮೂದಿಸಿ",
            "confirmPassword": "ಪಾಸ್‌ವರ್ಡ್ ದೃಢೀಕರಿಸಿ",
            "confirmPasswordPlaceholder": "ಪಾಸ್‌ವರ್ಡ್ ದೃಢೀಕರಿಸಿ",
            "optional": "(ಐಚ್ಛಿಕ)",
            "noCustomersFound": "ಯಾವುದೇ ಗ್ರಾಹಕರು ಕಂಡುಬಂದಿಲ್ಲ",
            "customerUpdated": "ಗ್ರಾಹಕರು ಯಶಸ್ವಿಯಾಗಿ ನವೀಕರಿಸಲಾಗಿದೆ",
            "customerCreated": "ಗ್ರಾಹಕರು ಯಶಸ್ವಿಯಾಗಿ ರಚಿಸಲಾಗಿದೆ",
            "error": "ದೋಷ",
            "nameRequired": "ಹೆಸರು ಅಗತ್ಯವಿದೆ",
            "invalidEmail": "ಅಮಾನ್ಯ ಇಮೇಲ್ ವಿಳಾಸ",
            "invalidPhone": "ಅಮಾನ್ಯ ಫೋನ್ ಸಂಖ್ಯೆ (10 ಅಂಕಿಗಳು ಅಗತ್ಯವಿದೆ)",
            "passwordLength": "ಪಾಸ್‌ವರ್ಡ್ ಕನಿಷ್ಠ 8 ಅಕ್ಷರಗಳನ್ನು ಹೊಂದಿರಬೇಕು",
            "passwordsDoNotMatch": "ಪಾಸ್‌ವರ್ಡ್‌ಗಳು ಹೊಂದಿಕೆಯಾಗುವುದಿಲ್ಲ",

            "selectLanguage": "ಭಾಷೆಯನ್ನು ಆಯ್ಕೆಮಾಡಿ",
            "reports": "ವರದಿಗಳು",
            "weeklyReport": "ಸಾಪ್ತಾಹಿಕ ವರದಿ",
            "verifyReport": "ಪರಿಶೀಲನೆ ವರದಿ",
            "addPaymentReport": "ಪಾವತಿ ವರದಿ ಸೇರಿಸಿ",
            "addButtonReport": "ಬಟನ್ ವರದಿ ಸೇರಿಸಿ",
            "dailyResult": "ದೈನಂದಿನ ಫಲಿತಾಂಶ",
            "result": "ಫಲಿತಾಂಶ",
            "agentList": "ಏಜೆಂಟ್ ಪಟ್ಟಿ",
            "clientList": "ಕ್ಲೈಂಟ್ ಪಟ್ಟಿ",
            "customerlist": "ಗ್ರಾಹಕ ಪಟ್ಟಿ",
            "mywallet": "ನನ್ನ ವಾಲೆಟ್",

            // Dashboard Screen Additional Translations
            "enterGunule": "ಗುನುಲೆ ನಮೂದಿಸಿ",
            "saralPanNumber": "ಸರಳ ಪ್ಯಾನ್ ಸಂಖ್ಯೆ",
            "ultaPanNumber": "ಉಲ್ಟಾ ಪ್ಯಾನ್ ಸಂಖ್ಯೆ",
            "addSaralPan": "ಸರಳ-ಪ್ಯಾನ್ ಸೇರಿಸಿ",
            "addGunule": "ಗುನುಲೆ ಸೇರಿಸಿ",
            "number": "ಸಂಖ್ಯೆ",
            "amount": "ಮೊತ್ತ",
            "action": "ಕ್ರಿಯೆ",
            "gunule": "ಗುನುಲೆ",
            "totalAmount": "ಒಟ್ಟು ಮೊತ್ತ",
            "openAmount": "ತೆರೆದ ಮೊತ್ತ",
            "closeAmount": "ಮುಚ್ಚಿದ ಮೊತ್ತ",
            "payNow": "ಈಗ ಪಾವತಿಸಿ",
            "confirmPayment": "ಪಾವತಿ ದೃಢೀಕರಿಸಿ",
            "paymentMessage": "ನೀವು {count} ನಮೂದುಗಳಿಗೆ ₹{amount} ಪಾವತಿಸಲು ಹೊರಟಿದ್ದೀರಿ.",
            "selectAtLeastOne": "ದಯವಿಟ್ಟು ಪಾವತಿಸಲು ಕನಿಷ್ಠ ಒಂದು ನಮೂದನ್ನು ಆಯ್ಕೆಮಾಡಿ",
            "confirmDelete": "ನೀವು ಖಚಿತವಾಗಿ ಈ ನಮೂದನ್ನು ಅಳಿಸಲು ಬಯಸುವಿರಾ?",
            "invalidNumber": "{category} ವರ್ಗಕ್ಕೆ ಅಮಾನ್ಯ ಸಂಖ್ಯೆ ಸ್ವರೂಪ",
            "pleaseEnterBoth": "ದಯವಿಟ್ಟು ಸಂಖ್ಯೆ ಮತ್ತು ಮೊತ್ತ ಎರಡನ್ನೂ ನಮೂದಿಸಿ",
            "addNumber": "ಸಂಖ್ಯೆ ಸೇರಿಸಿ",
            "removeNumber": "ಸಂಖ್ಯೆ ತೆಗೆಯಿರಿ",

            // Settings Screen - Password Change
            "changePassword": "ಪಾಸ್‌ವರ್ಡ್ ಬದಲಾಯಿಸಿ",
            "newPassword": "ಹೊಸ ಪಾಸ್‌ವರ್ಡ್",
            "updatePassword": "ಪಾಸ್‌ವರ್ಡ್ ಅಪ್‌ಡೇಟ್ ಮಾಡಿ",
            "updating": "ಅಪ್‌ಡೇಟ್ ಆಗುತ್ತಿದೆ...",
            "passwordChangedSuccessfully": "ಪಾಸ್‌ವರ್ಡ್ ಯಶಸ್ವಿಯಾಗಿ ಬದಲಾಯಿಸಲಾಗಿದೆ",
            "passwordChangeFailed": "ಪಾಸ್‌ವರ್ಡ್ ಬದಲಾಯಿಸಲು ವಿಫಲವಾಗಿದೆ",
            "allFieldsRequired": "ಎಲ್ಲಾ ಕ್ಷೇತ್ರಗಳು ಅಗತ್ಯವಿದೆ",

            // Registration validation messages
            "registrationFailed": "ನೋಂದಣಿ ವಿಫಲವಾಗಿದೆ. ದಯವಿಟ್ಟು ಮತ್ತೆ ಪ್ರಯತ್ನಿಸಿ."
        }
    }
};